name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Upload build to server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PATH: /var/www/your-app/build
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        # Copy the build directory to the server using SSH
        mkdir -p /tmp/build
        cp -r build/* /tmp/build
        scp -r -i $PRIVATE_KEY /tmp/build/* $SERVER_USER@$SERVER_HOST:$SERVER_PATH
        rm -rf /tmp/build
